### ISSUE TITLE
File/folder icons?

### ISSUE THREAD

**Issue by InfiniteCoder01** [quicken/filefocus#10]
I miss icons here. And context menu with options like in vscode explorer would be nice

**Comment by InfiniteCoder01** [comment]
I see, that icons are supported, however I don't understand, why folders don't have icons.
VSCode version: 1.82.1
Extension version: 1.5.4
Screenshot:
![image](https://github.com/quicken/filefocus/assets/66557254/581af06b-6fb0-4112-b813-9ca56974623b)

**Comment by quicken** [comment]
Thanks for reporting this issue.

 I have now fixed this bug. See this commit for details.
 
 https://github.com/quicken/filefocus/commit/9003d622800d2ceedbae50e9b9546dc33a191aa8

However, the updated icon theme defaults to NOT showing any icon for a folder. This appears to be the same behaviour as the file explorer built into VSCode.

Essentially, making the extension behave similarly to the file explore means no icons are displayed. (At list on my system.)

**Comment by quicken** [comment]
this issue has been fixed and will a part of the next release.
