### ISSUE TITLE
Enable full right-click context menu for files and folders

### ISSUE THREAD

**Issue by iwino** [quicken/filefocus#13]
File Focus is such a sorely needed feature that should be natively built into VS Code.

So, it's a real shame that the extension provides almost non-existent right-click context menu!

For folders, the right-click context menu only provides three options: new file, new folder, and rename.

For files, right-clicking a file only provides the option to rename the file. Even that is limited to files that are added to manually created groups only, as any file added to "glob groups" does not even get any right-click context menu at all!

Such a fine file management tool but marred by almost non-existent right-click context menu.

So, please give the full context menu when right-clicking files and folders, including custom menu items that are added by other extensions.

**Comment by quicken** [comment]
Heya,
I understand wanting the full context menu functionality. It is something I personally really wanted when I first built the extension and still do. 

Unfortunately, there currently is no way to my knowledge of actually hooking into the built in file context menu. So it comes down to rebuilding each piece of functionality from scratch. That of course is not possible as other extensions can contribute menu items to the context menu.

So hopefully at some point, the VSCode devs will add a feature that enables opening their file context menu from a third-party extension. 

Until that is possible the only option is to re-implement each functionality which is something I have done for the bare minimum features. Hopefully that at least explains why this "feature" is not currently available. As per always if someone can figure our some workaround that would be brilliant.

**Comment by iwino** [comment]
I see. Well, thank you for the extension. I'll close this issue.
