### ISSUE TITLE
FR: Add file to focus group from Open Editors panel

### ISSUE THREAD

**Issue by jawshooah** [quicken/filefocus#6]
Currently you can only add files to a focus group via the File Explorer panel. I often have that minimized and Open Editors expanded along with File Focus, so it would be nice to be able to add files to a focus group from there.

**Comment by quicken** [comment]
I have now done a fair bit of research to implement this functionality. However, unfortunately, there currently appears to be no mechanism for an extension to hook into the "Open Editors" file context menu.

As such, I will close this request out. I have added your request to my "investigate" later list and will keep an eye out for this capability being available as more features are made available to extension developers by the VSCode team.

I hope the extension is continuing to be useful for you.

**Comment by quicken** [comment]
.
